---
title: "5 baskets, individual species"
output: html_document
---

```{r}
# erase
rm(list = ls(all = TRUE)) 
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(ggplot2)
library(here)
library(quadprog)
library(future)
library(jsonlite)
library(purrr)
library(data.table)
```

```{r}
# Where to save datasets
fileplace <- "2species_gillnet"
# Type of model, in this case we have the simple scenarios
fileplace1 <- "2 single_sp"
```


# 1. Inputs

## Step 1: Input parameters
```{r}
# Species:
# s = species, r, K, X, p
k1 <- 8156.8715 #analis
k2 <- 163.63 #guttatus
#k3 <- 522.7108
#k4 <- 125.8112

p1 <- 2590.2
p2 <- 1914.21
#p3 <- 1749.82
#p4 <- 2398.5

r1 <- 0.3
r2 <- 0.4045

s1 <- c(s=1, r=r1, K=k1, X=k1*0.1, p=p1, tcoef=0) #analis
s2 <- c(s=2, r=r2, K=k2, X=k2*0.1, p=p2, tcoef=0) #guttatus


# t = tech, q1 = catchability species 1, q2 = catchability species 2...
qi1 <- 0.0008
qi2 <- 0.001
#qi3 <- 0.0006
#qi4 <- 0.000874
#qi5 <- 0.000874
#qi6 <- 0.000874
  
qi7 <- 0
  
t1 <- c(t=1, q1 = qi1, q2 = qi7)
t2 <- c(t=2, q1 = qi7, q2 = qi2)



# Tech cost: t = tech, cost = cost per unit effort
c1 <- c(t=1, cost=1)
c2 <- c(t=2, cost=1)

# Baskets: bimary matrix of # species x # baskets, where 1 means that species is in that basket

b1 <- c(s1 = 1, s2 = 0)
b2 <- c(s1 = 0, s2 = 1)

# Years
years = 30

# define base, max and min temp

temp_min=19
temp_max=26
# temp = runif(years, min = temp_min, max = temp_max) 

temp = c(24.96186, 22.78344, 23.18393, 21.37994, 21.63414, 22.50235, 21.18345, 25.96468, 
         20.91578, 19.54157, 23.54480, 24.30295, 20.24743, 25.40967, 20.77083, 22.85526, 
         21.43720, 25.29788, 19.55776, 23.66476, 24.93708, 23.00850, 24.87281, 23.02251, 
         23.28070, 24.51235, 19.96620, 20.82423, 25.95001, 24.94559)


temp_base=mean(unlist(temp))

# define SST anomaly
temp_anom=temp-temp_base

# without normalization
```

# Step 2: make a list of the inputs
```{r}
# Change these to reflect the number of species and technologies above:
species = list(s1, s2)
tech = list(t1, t2)
cost = list(c1, c2)
baskets = list(b1, b2)

sp_df <- as.data.frame(do.call(rbind, species))
tech_df <- as.data.frame(do.call(rbind, tech))
cost_df <- as.data.frame(do.call(rbind, cost))
baskets_df <- as.data.frame(do.call(rbind, baskets))

```

# Step 3: Run the function


```{r}

source(here("functions", "optimal_baskets.R"))
source(here("functions", "qb_stock_m.R"))

s1h <- 0.1
s2h <- 0.1


# mortality <- c(s1h, s2h, s3h, s4h, s5h)
# mortguess1  <-  t(as.matrix(mortality))
# mortguess1= t(as.matrix(c(s1h,s2h, s3h, s4h, s5h)))
mort_guess = c(s1h, s2h)
#mort_guess= t(mort_guess)

output <- optimal_baskets(species, tech, cost, baskets, mort_guess, years)

#source(here("functions_cc_fixed", "qb_stock_m_cc.R"))
#output <- qb_stock(species, tech, cost, baskets, mortality = mort_guess, years)

# Save the Bellman equation results
dt_list <- map(output, as.data.table)
dt <- rbindlist(dt_list, fill = TRUE, idcol = T)
```



```{r}
# file names
csvname <- "2spe_single.csv"
csvfile <- paste(csvname, sep="")


write.table(na.omit(output),here(fileplace1, fileplace,"results", csvfile),
              row.names=FALSE, sep=",")
```

